import json
import os

# Define the vocabulary data
vocab_data = {
    'Financial': [
        # Existing terms
        {'term': 'Going Concern', 'jp': '継続企業の前提', 'desc': '企業が将来にわたって事業を継続するという前提。', 'desc_en': 'The assumption that an entity will continue to operate for the foreseeable future.'},
        {'term': 'Accrual Basis', 'jp': '発生主義', 'desc': '現金の収支にかかわらず、経済的事象の発生時点で収益・費用を認識する原則。', 'desc_en': 'The principle of recognizing revenues and expenses when they occur, regardless of cash flow.'},
        {'term': 'Materiality', 'jp': '重要性', 'desc': '財務諸表利用者の意思決定に影響を与える情報の性質や金額の大きさ。', 'desc_en': 'The significance of information that could influence the economic decisions of users.'},
        {'term': 'Impairment', 'jp': '減損', 'desc': '資産の収益性が低下した結果、投資額の回収が見込めなくなった場合に帳簿価額を減額すること。', 'desc_en': 'A reduction in the carrying amount of an asset when its recoverable amount is less than its carrying value.'},
        {'term': 'Asset Retirement Obligation', 'jp': '資産除去債務', 'desc': '有形固定資産の取得や使用によって生じる、除去に関する将来の法的義務。', 'desc_en': 'A legal obligation associated with the retirement of a tangible long-lived asset.'},
        {'term': 'Fair Value', 'jp': '公正価値', 'desc': '市場参加者間で秩序ある取引が行われた場合に成立する価格。', 'desc_en': 'The price that would be received to sell an asset in an orderly transaction between market participants.'},
        {'term': 'Deferred Tax Asset', 'jp': '繰延税金資産', 'desc': '将来の税金を減らす効果がある一時差異。回収可能性の検討が必要。', 'desc_en': 'An asset representing future tax deductions arising from temporary differences.'},
        {'term': 'Equity Method', 'jp': '持分法', 'desc': '投資会社の持分に応じて、被投資会社の損益等を反映させる会計処理。関連会社等に適用。', 'desc_en': 'An accounting method for investments where the investor recognizes their share of the investee profits/losses.'},
        {'term': 'Goodwill', 'jp': 'のれん', 'desc': '企業買収等の際に支払った対価が、受け入れた純資産の時価を上回る超過収益力。', 'desc_en': 'An intangible asset arising from a business combination, representing the excess of purchase price over fair value of net assets.'},
        {'term': 'Comprehensive Income', 'jp': '包括利益', 'desc': '純資産の変動額のうち、資本取引によらない部分。当期純利益＋その他の包括利益。', 'desc_en': 'The change in equity during a period from transactions and other events, excluding those with owners.'},
        {'term': 'Provision', 'jp': '引当金', 'desc': '将来の特定の費用や損失に備えて、当期の費用として計上される金額。', 'desc_en': 'A liability of uncertain timing or amount.'},
        {'term': 'Contingent Liability', 'jp': '偶発債務', 'desc': '将来の事象の発生・不発生によって債務が確定する潜在的な義務。', 'desc_en': 'A potential obligation that depends on the outcome of a future event.'},
        {'term': 'Functional Currency', 'jp': '機能通貨', 'desc': '企業が営業活動を行う主たる経済環境の通貨。', 'desc_en': 'The currency of the primary economic environment in which the entity operates.'},
        {'term': 'Revaluation Surplus', 'jp': '再評価剰余金', 'desc': '資産の再評価（時価評価）によって生じた純資産の増加額。', 'desc_en': 'An equity reserve created when an asset is revalued at a higher amount than its carrying value.'},
        {'term': 'Retained Earnings', 'jp': '利益剰余金', 'desc': '企業が過去に獲得した利益のうち、配当せずに内部留保したもの。', 'desc_en': 'The cumulative net income of a company less any dividends declared.'},
        {'term': 'Non-controlling Interest', 'jp': '非支配株主持分', 'desc': '子会社の資本のうち、親会社に帰属しない部分。', 'desc_en': 'The portion of equity ownership in a subsidiary not attributable to the parent company.'},
        {'term': 'Cash Flow Statement', 'jp': 'キャッシュ・フロー計算書', 'desc': '一会計期間における現金の流入と流出を表す財務諸表。', 'desc_en': 'A financial statement that summarizes the amount of cash and cash equivalents entering and leaving a company.'},
        {'term': 'Inventory Valuation', 'jp': '棚卸資産評価', 'desc': '取得原価と正味売却価額のいずれか低い方で評価する（低価法）。', 'desc_en': 'Valuation at the lower of cost or net realizable value.'},
        {'term': 'Revenue Recognition', 'jp': '収益認識', 'desc': '顧客への財・サービスの移転時に、その対価として権利を得ると見込まれる金額で収益を認識すること。', 'desc_en': 'Recognizing revenue when goods or services are transferred to customers.'},
        {'term': 'Intangible Assets', 'jp': '無形資産', 'desc': '物理的実体を持たない識別可能な非貨幣性資産（特許権、商標権など）。', 'desc_en': 'Identifiable non-monetary assets without physical substance.'},
        {'term': 'Financial Instruments', 'jp': '金融商品', 'desc': '一方の企業に金融資産を生じさせ、他方の企業に金融負債または資本性金融商品を生じさせる契約。', 'desc_en': 'Contracts that give rise to a financial asset of one entity and a financial liability or equity instrument of another entity.'},
        {'term': 'Consolidated Financial Statements', 'jp': '連結財務諸表', 'desc': '親会社と子会社を単一の経済的実体とみなして作成される財務諸表。', 'desc_en': 'Financial statements of a group presented as those of a single economic entity.'},
        # New Terms
        {'term': 'Deferred Assets', 'jp': '繰延資産', 'desc': '支出の効果が将来に及ぶ費用を資産として計上したもの（創立費など）。', 'desc_en': 'Expenses treated as assets because their benefits extend to future periods.'},
        {'term': 'Research and Development (R&D)', 'jp': '研究開発費', 'desc': '新しい知識の発見や新しい製品・プロセスの開発のために支出される費用。発生時に費用処理。', 'desc_en': 'Expenses incurred in the process of finding and creating new products or knowledge.'},
        {'term': 'Lease Accounting', 'jp': 'リース会計', 'desc': 'リース取引をファイナンス・リースとオペレーティング・リースに区分し、資産・負債として認識する会計処理。', 'desc_en': 'Accounting for the rights and obligations arising from lease contracts.'},
        {'term': 'Tax Effect Accounting', 'jp': '税効果会計', 'desc': '企業会計上の利益と税務上の所得のズレ（一時差異）を調整し、適切な期間配分を行う手続き。', 'desc_en': 'Accounting for the differences between accounting income and taxable income.'},
        {'term': 'Segment Information', 'jp': 'セグメント情報', 'desc': '企業の事業別や地域別の財務情報を開示すること。投資家の意思決定に有用。', 'desc_en': 'Reporting financial information by distinct business activities or geographical areas.'},
        {'term': 'Earnings Per Share (EPS)', 'jp': '1株当たり当期純利益', 'desc': '当期純利益を発行済株式数で割った指標。企業の収益性を示す。', 'desc_en': 'Net income divided by the number of outstanding shares.'},
        {'term': 'Diluted EPS', 'jp': '潜在株式調整後1株当たり当期純利益', 'desc': 'ストックオプションや転換社債などの権利行使を仮定した場合のEPS。', 'desc_en': 'EPS calculated assuming all convertible securities are exercised.'},
        {'term': 'Cash Equivalents', 'jp': '現金同等物', 'desc': '容易に換金可能で、価値変動リスクが僅少な短期投資（3ヶ月以内）。', 'desc_en': 'Short-term, highly liquid investments requiring 3 months or less to maturity.'},
        {'term': 'Bad Debt Expense', 'jp': '貸倒引当金繰入', 'desc': '回収不能と見込まれる債権に対する費用計上。', 'desc_en': 'Expense recognized for estimated uncollectible accounts.'},
        {'term': 'Allowance for Doubtful Accounts', 'jp': '貸倒引当金', 'desc': '売掛金などの債権が回収不能になるリスクに備えるための評価勘定。', 'desc_en': 'A contra-asset account representing the estimated uncollectible accounts receivable.'},
        {'term': 'Depreciation', 'jp': '減価償却', 'desc': '有形固定資産の取得原価を耐用年数にわたって費用配分する手続き。', 'desc_en': 'Allocating the cost of a tangible asset over its useful life.'},
        {'term': 'Amortization', 'jp': '償却（無形資産）', 'desc': '無形固定資産の取得原価を耐用年数にわたって費用配分する手続き。', 'desc_en': 'Allocating the cost of an intangible asset over its useful life.'},
        {'term': 'Construction in Progress', 'jp': '建設仮勘定', 'desc': '完成前の有形固定資産への支出を集計する勘定。減価償却は行わない。', 'desc_en': 'Asset account representing costs incurred for assets under construction.'},
        {'term': 'Negative Goodwill', 'jp': '負ののれん', 'desc': '買収対価が受け入れ純資産の時価を下回る場合に発生する差益。発生益として計上。', 'desc_en': 'The gain recognized when the price paid for an acquisition is less than the fair value of net assets.'},
        {'term': 'Stock Swap', 'jp': '株式交換', 'desc': 'ある会社が他の会社の株式を100%取得し、完全子会社化する組織再編手法。', 'desc_en': 'A corporate reorganization where a company becomes a wholly owned subsidiary via share exchange.'},
        {'term': 'Stock Transfer', 'jp': '株式移転', 'desc': '既存の会社が単独または共同で持株会社（親会社）を設立し、その傘下に入る手法。', 'desc_en': 'Establishing a new holding company by transferring shares of existing companies.'},
        {'term': 'Corporate Bond', 'jp': '社債', 'desc': '企業が資金調達のために発行する債券。負債として計上。', 'desc_en': 'Debt security issued by a corporation and sold to investors.'},
        {'term': 'Convertible Bond (CB)', 'jp': '転換社債型新株予約権付社債', 'desc': '一定の条件で株式に転換できる権利（新株予約権）が付いた社債。', 'desc_en': 'A bond that can be converted into a predetermined number of shares of common stock.'},
        {'term': 'Warrant', 'jp': '新株予約権', 'desc': 'あらかじめ決められた価格で株式を購入できる権利。', 'desc_en': 'A derivative that confers the right, but not the obligation, to buy or sell a security.'},
        {'term': 'Legal Reserve', 'jp': '利益準備金', 'desc': '会社法により積立が義務付けられている準備金。配当原資の1/10など。', 'desc_en': 'Reserves required by law to be set aside from profits.'},
        {'term': 'Capital Surplus', 'jp': '資本剰余金', 'desc': '株主からの払込金のうち資本金に組み入れなかった部分（資本準備金）など。', 'desc_en': 'Equity derived from sources other than earnings, such as paid-in capital.'},
        {'term': 'Treasury Stock Deduction', 'jp': '自己株式の控除', 'desc': '自己株式は資産ではなく、純資産の控除項目として表示される。', 'desc_en': 'Treasury stock is reported as a deduction from shareholders\' equity.'},
        {'term': 'Non-operating Income', 'jp': '営業外収益', 'desc': '本業以外の活動から生じる収益（受取利息、配当金など）。', 'desc_en': 'Income derived from activities not related to core business operations.'},
        {'term': 'Extraordinary Loss', 'jp': '特別損失', 'desc': '通常発生しない臨時的・巨額な損失（災害損失、固定資産売却損など）。', 'desc_en': 'Losses from events that are unusual and infrequent.'},
        {'term': 'Current Ratio', 'jp': '流動比率', 'desc': '流動資産÷流動負債。短期的な支払能力を示す指標。200%以上が望ましいとされる。', 'desc_en': 'Liquidity ratio measuring ability to pay short-term obligations (Current Assets / Current Liabilities).'},
        {'term': 'Quick Ratio', 'jp': '当座比率', 'desc': '当座資産÷流動負債。より厳密な短期支払能力を示す。100%以上が望ましい。', 'desc_en': 'Indicator of a company’s short-term liquidity (Quick Assets / Current Liabilities).'},
        {'term': 'Debt Ratio', 'jp': '負債比率', 'desc': '負債総額÷自己資本。企業の財務安全性を測る指標。低いほうが安全。', 'desc_en': 'Ratio indicating the proportion of debt used to finance assets.'},
        {'term': 'ROE (Return on Equity)', 'jp': '自己資本利益率', 'desc': '当期純利益÷自己資本。株主の持分に対する収益性を示す。', 'desc_en': 'Measure of financial performance calculated by dividing net income by shareholders\' equity.'},
        {'term': 'ROA (Return on Assets)', 'jp': '総資産利益率', 'desc': '当期純利益÷総資産。資産全体の運用効率を示す。', 'desc_en': 'Indicator of how profitable a company is relative to its total assets.'},
        {'term': 'Turnover Ratio', 'jp': '回転率', 'desc': '売上高÷資産（売掛金、棚卸資産など）。資産の効率性を示す。', 'desc_en': 'Efficiency ratio indicating how effectively assets are used.'},
        {'term': 'Operating Cycle', 'jp': '営業循環', 'desc': '現金→仕入→在庫→販売→売掛金→現金のサイクル。', 'desc_en': 'The time it takes to convert inventory into cash.'},
        {'term': 'Working Capital', 'jp': '運転資本', 'desc': '流動資産－流動負債。事業継続に必要な手元資金。', 'desc_en': 'Capital of a business which is used in its day-to-day trading operations.'},
        {'term': 'Direct Method', 'jp': '直接法（CF）', 'desc': '営業CFの表示方法の一つ。主要な取引ごとの現金の受払を総額で表示する。', 'desc_en': 'Reporting cash flows from operating activities by listing major classes of gross cash receipts and payments.'},
        {'term': 'Indirect Method', 'jp': '間接法（CF）', 'desc': '税引前当期純利益から非資金項目や運転資本の増減を加減算して営業CFを求める方法。', 'desc_en': 'Reporting cash flows from operating activities by adjusting net income for non-cash items.'},
        {'term': 'Investing Activities', 'jp': '投資活動', 'desc': '固定資産や有価証券の取得・売却によるキャッシュフロー。', 'desc_en': 'Cash flows from acquisition and disposal of long-term assets.'},
        {'term': 'Financing Activities', 'jp': '財務活動', 'desc': '借入や株式発行、配当金の支払いなど、資金調達に関連するキャッシュフロー。', 'desc_en': 'Cash flows giving rise to changes in the size and composition of contributed equity and borrowings.'},
        {'term': 'IFRS', 'jp': '国際財務報告基準', 'desc': '国際会計基準審議会（IASB）が設定する会計基準。', 'desc_en': 'International Financial Reporting Standards issued by the IASB.'},
        {'term': 'GAAP', 'jp': '一般に公正妥当と認められた会計原則', 'desc': '各国の制度会計の基礎となるルール（US GAAP, J-GAAPなど）。', 'desc_en': 'Generally Accepted Accounting Principles.'},
        {'term': 'Conceptual Framework', 'jp': '概念フレームワーク', 'desc': '会計基準開発の基礎となる理論的枠組み。', 'desc_en': 'A body of interrelated objectives and fundamentals for financial reporting.'},
        {'term': 'Recognition Criteria', 'jp': '認識要件', 'desc': 'いつ、どの項目を財務諸表に計上するかを決定する基準。', 'desc_en': 'Conditions to be met for an item to be recognized in financial statements.'},
        {'term': 'Historical Cost', 'jp': '取得原価', 'desc': '資産を取得した時点の支出額で評価する考え方。確実性が高い。', 'desc_en': 'The original nominal value of an economic item.'},
        {'term': 'Current Cost', 'jp': '再調達原価', 'desc': '現在その資産を取得するとしたらかかる金額。', 'desc_en': 'The cost that would be required to replace an asset in the current period.'},
        {'term': 'Present Value', 'jp': '現在価値', 'desc': '将来のキャッシュフローを割引率を用いて現在時点の価値に換算した金額。', 'desc_en': 'The current value of a future sum of money or stream of cash flows given a specified rate of return.'},
        {'term': 'Consistency', 'jp': '継続性', 'desc': '一度採用した会計方針は、正当な理由がない限り毎期継続して適用すべきという原則。', 'desc_en': 'The principle that the same accounting methods should be used from year to year.'},
        {'term': 'Conservatism', 'jp': '保守主義', 'desc': '不確実性に直面した際、利益を控えめに、損失を早めに計上する慎重な判断。', 'desc_en': 'The principle of anticipating and recognizing losses immediately, but recognizing gains only when realized.'},
        {'term': 'Substance Over Form', 'jp': '実質優先', 'desc': '法的形式よりも経済的実質を重視して会計処理を行う原則。', 'desc_en': 'The concept that financial statements should reflect the underlying economic reality rather than the legal form.'},
        {'term': 'Principal-Agent', 'jp': '本人・代理人', 'desc': '収益認識において、自らが当事者（本人）か、手配者（代理人）かによって売上計上額（総額vs純額）が異なる。', 'desc_en': 'Determining whether an entity is acting as a principal or an agent affects revenue recognition (Gross vs Net).'},
        {'term': 'Performance Obligation', 'jp': '履行義務', 'desc': '顧客との契約において、財・サービスを移転する約束。収益認識の単位。', 'desc_en': 'A promise in a contract with a customer to transfer a distinct good or service.'},
        {'term': 'Transaction Price', 'jp': '取引価格', 'desc': '財・サービスの移転と交換に、企業が権利を得ると見込む対価の額。', 'desc_en': 'The amount of consideration to which an entity expects to be entitled.'},
        {'term': 'Bill-and-Hold', 'jp': '請求済未出荷契約', 'desc': '商品は顧客のために保管されているが、まだ出荷されていない状態で収益認識する取引。要件が厳しい。', 'desc_en': 'A contract under which an entity bills a customer for a product but the entity retains physical possession.'},
        {'term': 'Consignment', 'jp': '委託販売', 'desc': '商品を受託者に預け、受託者が最終顧客に販売した時点で収益を認識する取引。', 'desc_en': 'An arrangement where goods are left in the possession of another party to sell.'},
        {'term': 'Foreign Currency Transaction', 'jp': '外貨建取引', 'desc': '売買価額などが外国通貨で表示されている取引。為替レートによる換算が必要。', 'desc_en': 'A transaction that is denominated or requires settlement in a foreign currency.'},
        {'term': 'Translation Adjustment', 'jp': '為替換算調整勘定', 'desc': '海外子会社の財務諸表を換算する際に生じる差額。純資産の部に計上。', 'desc_en': 'Equity component arising from translating foreign subsidiary financial statements.'},
        {'term': 'Hedging', 'jp': 'ヘッジ取引', 'desc': '価格変動リスクや金利変動リスクなどを回避・軽減するための取引。', 'desc_en': 'Making an investment to reduce the risk of adverse price movements in an asset.'},
        {'term': 'Derivative', 'jp': 'デリバティブ', 'desc': '基礎となる数値（金利、株価など）の変動に応じて価値が決まる金融派生商品。', 'desc_en': 'A financial security with a value that is reliant upon or derived from an underlying asset.'},
        {'term': 'Forward Contract', 'jp': '先渡取引', 'desc': '将来の特定の日付に、特定の価格で資産を売買する相対契約。', 'desc_en': 'A customized contract between two parties to buy or sell an asset at a specified price on a future date.'},
        {'term': 'Future', 'jp': '先物取引', 'desc': '取引所を通じて行われる、標準化された先渡取引。', 'desc_en': 'Standardized forward contracts traded on an exchange.'},
        {'term': 'Option', 'jp': 'オプション', 'desc': '将来の特定の日付または期間内に、特定の価格で売買する「権利」の取引。', 'desc_en': 'A contract that gives the buyer the right, but not the obligation, to buy or sell an asset.'},
        {'term': 'Swap', 'jp': 'スワップ', 'desc': '将来にわたってキャッシュフローを交換する契約（金利スワップ、通貨スワップなど）。', 'desc_en': 'A derivative contract through which two parties exchange the cash flows or liabilities.'},
        {'term': 'Fair Value Hierarchy', 'jp': '公正価値ヒエラルキー', 'desc': '公正価値測定に用いるインプットの信頼性に応じた3つのレベル（レベル1が最も客観的）。', 'desc_en': 'Categorization of inputs used in valuation techniques into three levels.'},
        {'term': 'CGU (Cash Generating Unit)', 'jp': '資金生成単位', 'desc': '減損会計において、独立したキャッシュ・イン・フローを生み出す最小の資産グループ。', 'desc_en': 'The smallest identifiable group of assets that generates cash inflows.'},
        {'term': 'Finance Lease', 'jp': 'ファイナンス・リース', 'desc': '実質的に資産の売買とみなされるリース。解約不能かつフルペイアウトが条件。', 'desc_en': 'A lease that transfers substantially all the risks and rewards incidental to ownership.'},
        {'term': 'Operating Lease', 'jp': 'オペレーティング・リース', 'desc': 'ファイナンス・リース以外のリース。賃貸借取引として処理される（IFRS/新基準ではオンバランス化）。', 'desc_en': 'A lease whose term is short compared to the useful life of the asset or piece of equipment.'},
        {'term': 'Right-of-Use Asset', 'jp': '使用権資産', 'desc': 'リース期間にわたって原資産を使用する権利を表す資産。', 'desc_en': 'An asset that represents a lessee\'s right to use an underlying asset for the lease term.'},
        {'term': 'Lease Liability', 'jp': 'リース負債', 'desc': 'リース料を支払う義務を表す負債。現在価値で計上。', 'desc_en': 'The financial obligation for the payments required by a lease.'},
        {'term': 'Effective Tax Rate', 'jp': '実効税率', 'desc': '税効果会計適用後の、税引前利益に対する法人税等の比率。', 'desc_en': 'The average rate at which a corporation is taxed on pre-tax profits.'},
        {'term': 'Temporary Difference', 'jp': '一時差異', 'desc': '会計上の資産・負債と税務上の資産・負債の差額のうち、将来解消されるもの。', 'desc_en': 'Difference between the carrying amount of an asset/liability and its tax base.'},
        {'term': 'Permanent Difference', 'jp': '永久差異', 'desc': '交際費や受取配当金など、会計と税務で取り扱いが永久に一致しない項目。税効果の対象外。', 'desc_en': 'Differences between book and tax income that will never reverse.'},
        {'term': 'Specific Identification', 'jp': '個別法', 'desc': '個々の商品ごとに原価を管理し、売上原価を算定する方法。宝石や不動産など高額品に適する。', 'desc_en': 'Tracking the cost of each specific item in inventory.'},
        {'term': 'Moving Average', 'jp': '移動平均法', 'desc': '仕入の都度、平均単価を算出し直す棚卸資産評価方法。', 'desc_en': 'Recalculating the average cost per unit after every purchase.'},
        {'term': 'Weighted Average', 'jp': '総平均法', 'desc': '期首在庫と当期仕入の合計額を総数量で割って平均単価を算出する方法。', 'desc_en': 'Calculating average cost based on total cost of goods available for sale divided by total units.'},
        {'term': 'LIFO', 'jp': '後入先出法', 'desc': '最後に仕入れたものから先に売れたと仮定する方法（IFRSでは禁止）。', 'desc_en': 'Last-In, First-Out. Assumes newest inventory is sold first.'},
        {'term': 'FIFO', 'jp': '先入先出法', 'desc': '最初に仕入れたものから先に売れたと仮定する方法。物価上昇時は利益が大きくなる。', 'desc_en': 'First-In, First-Out. Assumes oldest inventory is sold first.'}
    ,        {'term': 'Unearned Revenue', 'jp': '前受収益', 'desc': '対価は受領済みだが、まだ提供していない財・サービスに対応する負債。', 'desc_en': 'A liability for consideration received before goods or services are delivered.'},
        {'term': 'Accrued Expenses', 'jp': '未払費用', 'desc': '発生しているが未払いの費用に対する負債。', 'desc_en': 'Expenses that have been incurred but not yet paid.'},
        {'term': 'Accrued Revenue', 'jp': '未収収益', 'desc': '提供済みだが未収の対価に対する資産。', 'desc_en': 'Revenue that has been earned but not yet billed or collected.'},
        {'term': 'Share-based Payment', 'jp': '株式報酬', 'desc': '従業員や役員への報酬を株式や新株予約権で行う取引の会計処理。', 'desc_en': 'Accounting for transactions where the entity receives goods or services as consideration for equity instruments.'},
        {'term': 'Borrowing Costs', 'jp': '借入費用', 'desc': '適格資産への支出に直接関連する借入費用は資産計上し、それ以外は費用処理。', 'desc_en': 'Borrowing costs directly attributable to the acquisition of a qualifying asset are capitalized; others are expensed.'}
    ],
    'Management': [
        # Existing terms
        {'term': 'Opportunity Cost', 'jp': '機会原価', 'desc': 'ある代替案を選択したことによって犠牲となった（諦めた）最大の利益。', 'desc_en': 'The potential benefit lost when one alternative is chosen over another.'},
        {'term': 'Sunk Cost', 'jp': '埋没原価', 'desc': '過去の意思決定によって既に発生し、回収不能なコスト。意思決定では無視すべき。', 'desc_en': 'A cost that has already been incurred and cannot be recovered.'},
        {'term': 'Break-even Point', 'jp': '損益分岐点', 'desc': '売上高と総費用が等しくなり、利益がゼロとなる点。', 'desc_en': 'The level of sales where total revenue equals total costs (zero profit).'},
        {'term': 'Safety Margin', 'jp': '安全余裕率', 'desc': '現在の売上高が損益分岐点をどれだけ上回っているかを示す指標。高いほど安全。', 'desc_en': 'The difference between actual sales and break-even sales.'},
        {'term': 'Cost Driver', 'jp': 'コスト・ドライバー', 'desc': '活動原価計算（ABC）において、コスト発生の原因となる活動量や要因。', 'desc_en': 'The factor that causes a change in the cost of an activity.'},
        {'term': 'Standard Costing', 'jp': '標準原価計算', 'desc': '科学的・統計的調査に基づいて設定された目標原価を用いて行う原価計算。', 'desc_en': 'A system of using predetermined costs for products or services for planning and control.'},
        {'term': 'Variance Analysis', 'jp': '差異分析', 'desc': '標準原価と実際原価の差額（差異）を分析し、原因を特定して管理に役立てる手法。', 'desc_en': 'The quantitative investigation of the difference between actual and standard behavior.'},
        {'term': 'Direct Costing', 'jp': '直接原価計算', 'desc': '原価を変動費と固定費に分解し、変動費のみを製品原価とする計算手法（CVP分析に有用）。', 'desc_en': 'A costing method that only assigns variable costs to products (useful for CVP analysis).'},
        {'term': 'ROI (Return on Investment)', 'jp': '投下資本利益率', 'desc': '投資した資本に対してどれだけの利益を上げたかを示す収益性指標。', 'desc_en': 'A performance measure used to evaluate the efficiency of an investment.'},
        {'term': 'Balanced Scorecard', 'jp': 'バランスト・スコアカード', 'desc': '財務、顧客、業務プロセス、学習と成長の4つの視点から業績を評価する手法。', 'desc_en': 'A strategic management performance metric used to identify and improve internal business functions.'},
        {'term': 'Just-In-Time (JIT)', 'jp': 'ジャスト・イン・タイム', 'desc': '必要なものを、必要な時に、必要な量だけ生産・供給する生産方式。', 'desc_en': 'An inventory strategy to increase efficiency by receiving goods only as they are needed.'},
        {'term': 'Kaizen Costing', 'jp': '改善原価計算', 'desc': '製造段階において、継続的な改善活動を通じて原価低減を図る手法。', 'desc_en': 'A system of continuous improvement in cost reduction during the manufacturing phase.'},
        {'term': 'Activity-Based Costing (ABC)', 'jp': '活動基準原価計算', 'desc': '間接費を活動（アクティビティ）ごとに集計し、活動量（コストドライバー）に基づいて製品に配賦する手法。', 'desc_en': 'A costing method that assigns overhead and indirect costs to related products and services.'},
        {'term': 'Target Costing', 'jp': '原価企画', 'desc': '製品の企画・開発段階で目標原価を設定し、その達成を目指して原価を作り込む活動。', 'desc_en': 'A system under which a company plans in advance for the price points, product costs, and margins.'},
        {'term': 'Bottleneck', 'jp': 'ボトルネック', 'desc': '生産工程全体の中で能力が最も低く、全体の生産能力を制約している工程。', 'desc_en': 'A point of congestion in a production system that slows down the overall process.'},
        {'term': 'Contribution Margin', 'jp': '貢献利益', 'desc': '売上高から変動費を差し引いた利益。固定費の回収と営業利益の創出に貢献する。', 'desc_en': 'Sales revenue less variable costs.'},
        {'term': 'Variable Cost', 'jp': '変動費', 'desc': '操業度（生産量や売上高）の増減に比例して発生する原価。', 'desc_en': 'A corporate expense that changes in proportion to production output.'},
        {'term': 'Product Life Cycle', 'jp': '製品ライフサイクル', 'desc': '製品が市場に投入されてから撤退するまでのプロセス（導入期、成長期、成熟期、衰退期）。', 'desc_en': 'The succession of stages a product goes through from introduction to withdrawal.'},
        {'term': 'Transfer Pricing', 'jp': '振替価格', 'desc': '企業内の事業部門間で財・サービスを取引する際に設定される価格。', 'desc_en': 'The price at which goods and services are transferred between divisions of the same company.'},
        {'term': 'Economic Value Added (EVA)', 'jp': '経済的付加価値', 'desc': '税引後営業利益から資本コストを差し引いた、企業が生み出した真の経済的価値。', 'desc_en': 'A measure of a company\'s financial performance based on the residual wealth calculated by deducting its cost of capital from its operating profit.'},
        {'term': 'Learning Curve', 'jp': '学習曲線', 'desc': '累積生産量が増加するにつれて、単位当たりの労働時間やコストが一定の割合で減少する経験則。', 'desc_en': 'A graphical representation of the increase of learning (vertical axis) with experience (horizontal axis).'},
        {'term': 'Benchmarking', 'jp': 'ベンチマーキング', 'desc': '自社の製品やプロセスを、業界最高水準の他社と比較・分析し、改善を図る手法。', 'desc_en': 'Comparing one\'s business processes and performance metrics to industry bests and best practices.'},
        # New Terms
        {'term': 'Absorption Costing', 'jp': '全部原価計算', 'desc': '固定製造間接費を含めたすべての製造原価を製品に集計する方法（制度会計で要求される）。', 'desc_en': 'A costing method where all manufacturing costs are absorbed by the units produced.'},
        {'term': 'Operating Leverage', 'jp': '営業レバレッジ', 'desc': '固定費の存在により、売上高の変動が営業利益に拡大して影響する効果。', 'desc_en': 'The degree to which a firm or project incurs a combination of fixed and variable costs.'},
        {'term': 'Financial Leverage', 'jp': '財務レバレッジ', 'desc': '負債の利用により、ROEの変動幅が拡大する効果。', 'desc_en': 'The use of debt to acquire additional assets.'},
        {'term': 'Residual Income (RI)', 'jp': '残余利益', 'desc': '営業利益から、投下資本に対する資本コスト額を差し引いた利益。', 'desc_en': 'Net operating income that an investment center earns above the minimum required return on its operating assets.'},
        {'term': 'KPI (Key Performance Indicator)', 'jp': '重要業績評価指標', 'desc': '組織の目標達成度を定量的に評価するための指標。', 'desc_en': 'A measurable value that demonstrates how effectively a company is achieving key business objectives.'},
        {'term': 'SWOT Analysis', 'jp': 'SWOT分析', 'desc': '強み(Strengths)、弱み(Weaknesses)、機会(Opportunities)、脅威(Threats)の4要素で環境分析を行う手法。', 'desc_en': 'A strategic planning technique used to help a person or organization identify strengths, weaknesses, opportunities, and threats.'},
        {'term': 'Porter\'s 5 Forces', 'jp': '5フォース分析', 'desc': '業界の収益性を決める5つの競争要因（新規参入、代替品、買い手、売り手、競合）を分析する枠組み。', 'desc_en': 'A framework that identifies five forces that determine the profit potential of an industry.'},
        {'term': 'Value Chain', 'jp': 'バリューチェーン', 'desc': '企業の活動を価値創造の連鎖として捉え、どの工程で付加価値が生み出されているかを分析する概念。', 'desc_en': 'A set of activities that a firm operating in a specific industry performs in order to deliver a valuable product.'},
        {'term': 'PEST Analysis', 'jp': 'PEST分析', 'desc': '政治(Politics)、経済(Economy)、社会(Society)、技術(Technology)の視点からマクロ環境を分析する手法。', 'desc_en': 'A tool used to analyze and monitor the macro-environmental factors.'},
        {'term': 'PPM (Product Portfolio Management)', 'jp': 'プロダクト・ポートフォリオ・マネジメント', 'desc': '市場成長率と市場シェアの2軸で事業を分類し（花形、金のなる木など）、資源配分を決定する手法。', 'desc_en': 'A business framework used to evaluate the strategic position of a business brand portfolio.'},
        {'term': '4Ps', 'jp': 'マーケティング・ミックス(4P)', 'desc': 'Product, Price, Place, Promotionの4要素を組み合わせて戦略を立てること。', 'desc_en': 'The four key elements of a marketing strategy: Product, Price, Place, and Promotion.'},
        {'term': 'Budgeting', 'jp': '予算管理', 'desc': '将来の計画を数値化し、実績と比較して統制を行うマネジメント・システム。', 'desc_en': 'The process of creating a plan to spend your money.'},
        {'term': 'Flexible Budget', 'jp': '変動予算', 'desc': '実際の操業度に応じて予算額を修正し、業績評価を行う予算。', 'desc_en': 'A budget that adjusts or flexes for changes in the volume of activity.'},
        {'term': 'Zero-based Budgeting', 'jp': 'ゼロベース予算', 'desc': '前年度の実績を基準にせず、ゼロから必要性を検討して予算を編成する方法。', 'desc_en': 'A method of budgeting in which all expenses must be justified for each new period.'},
        {'term': 'Rolling Budget', 'jp': 'ローリング予算', 'desc': '期間が経過するごとに将来の予算を追加し、常に一定期間の予算を維持する方法。', 'desc_en': 'A budget that is continuously updated so that the next 12 months of operations are always budgeted.'},
        {'term': 'Capital Budgeting', 'jp': '設備投資意思決定', 'desc': '長期的な投資案件の採算性を評価し、投資するか否かを決定するプロセス。', 'desc_en': 'The process a business undertakes to evaluate potential major projects or investments.'},
        {'term': 'NPV (Net Present Value)', 'jp': '正味現在価値', 'desc': '将来のキャッシュフローの現在価値合計から投資額を差し引いた金額。プラスなら投資すべき。', 'desc_en': 'The difference between the present value of cash inflows and the present value of cash outflows.'},
        {'term': 'IRR (Internal Rate of Return)', 'jp': '内部収益率', 'desc': '投資の正味現在価値がゼロになるような割引率。期待収益率より高ければ投資すべき。', 'desc_en': 'The discount rate that makes the net present value of all cash flows equal to zero.'},
        {'term': 'Payback Period', 'jp': '回収期間法', 'desc': '投資額を回収するのに要する期間で投資判断を行う方法。短いほど良い。', 'desc_en': 'The amount of time it takes to recover the cost of an investment.'},
        {'term': 'Profitability Index', 'jp': '収益性指数', 'desc': '将来キャッシュフローの現在価値合計を投資額で割った比率。1より大きければ有利。', 'desc_en': 'The ratio of payoff to investment of a proposed project.'},
        {'term': 'Sensitivity Analysis', 'jp': '感度分析', 'desc': '前提条件（売上、コストなど）が変化したときに、結果（利益、NPVなど）がどれだけ変動するかを分析する手法。', 'desc_en': 'Determining how different values of an independent variable affect a particular dependent variable.'},
        {'term': 'Real Options', 'jp': 'リアル・オプション', 'desc': '金融オプションの理論を実物資産への投資判断に応用し、将来の不確実性に対する柔軟性を価値評価する手法。', 'desc_en': 'Choices available to managers concerning business investment opportunities.'},
        {'term': 'Dual Pricing', 'jp': '二重価格制', 'desc': '振替価格において、供給部門には市場価格、受入部門には原価など、異なる価格を適用する方法。', 'desc_en': 'Using different transfer prices for the selling and buying divisions.'},
        {'term': 'Throughput Accounting', 'jp': 'スループット会計', 'desc': '制約理論（TOC）に基づき、スループット（売上－資材費）の最大化を目指す会計手法。', 'desc_en': 'A management accounting technique used to identify factors that limit an organization from achieving its goal.'},
        {'term': 'Lean Production', 'jp': 'リーン生産方式', 'desc': 'ムダを徹底的に排除し、顧客価値を最大化する生産システム。トヨタ生産方式が起源。', 'desc_en': 'A systematic method for waste minimization within a manufacturing system.'},
        {'term': 'Six Sigma', 'jp': 'シックス・シグマ', 'desc': '統計的手法を用いてプロセスを改善し、欠陥（ばらつき）を極限まで減らす品質管理手法。', 'desc_en': 'A set of techniques and tools for process improvement.'},
        {'term': 'Quality Cost', 'jp': '品質原価', 'desc': '品質を維持・向上させるためのコスト（予防原価、評価原価）と、品質不良によるコスト（失敗原価）。', 'desc_en': 'The cost associated with preventing, detecting, and remediating product issues.'},
        {'term': 'Make or Buy', 'jp': '内製・外注の決定', 'desc': '製品や部品を自社で製造するか、外部から購入するかをコスト比較により決定すること。', 'desc_en': 'The act of choosing between manufacturing a product in-house or purchasing it from an external supplier.'},
        {'term': 'Special Order', 'jp': '追加注文の受諾', 'desc': '通常価格より低い価格での追加注文に対し、遊休能力がある場合に変動費を回収できれば受諾すべきという判断。', 'desc_en': 'A one-time order that is not considered part of the company\'s normal ongoing business.'},
        {'term': 'Product Mix', 'jp': 'プロダクト・ミックス', 'desc': '制約条件（ボトルネック）がある中で、利益を最大化するための製品の生産・販売の組み合わせ。', 'desc_en': 'The total set of products offered by a company.'},
        {'term': 'Linear Programming (LP)', 'jp': '線形計画法', 'desc': '制約条件下での最大化・最小化問題を数学的に解く手法。', 'desc_en': 'A method to achieve the best outcome in a mathematical model whose requirements are represented by linear relationships.'},
        {'term': 'Game Theory', 'jp': 'ゲーム理論', 'desc': '利害関係を持つ複数の主体（プレイヤー）が、互いの行動を予測しながら意思決定を行う状況を分析する理論。', 'desc_en': 'The study of mathematical models of strategic interaction among rational decision-makers.'},
        {'term': 'Nash Equilibrium', 'jp': 'ナッシュ均衡', 'desc': '各プレイヤーが、相手の戦略に対して最適な戦略を選んでおり、誰も戦略を変更する誘因がない状態。', 'desc_en': 'A stable state of a system involving the interaction of different participants.'},
        {'term': 'Prisoner\'s Dilemma', 'jp': '囚人のジレンマ', 'desc': '個々にとって最適な選択が、全体としては最悪の結果を招く状況を示すゲーム理論のモデル。', 'desc_en': 'A paradox in decision analysis in which two individuals acting in their own self-interests do not produce the optimal outcome.'},
        {'term': 'Agency Theory', 'jp': 'エージェンシー理論', 'desc': '依頼人（プリンシパル）と代理人（エージェント）の間の情報の非対称性や利害対立を分析する理論。', 'desc_en': 'A principle that is used to explain and resolve issues in the relationship between business principals and their agents.'},
        {'term': 'Moral Hazard', 'jp': 'モラル・ハザード', 'desc': '契約後、情報を持つ側（エージェント）が、持たない側（プリンシパル）の利益に反する行動をとること。', 'desc_en': 'Lack of incentive to guard against risk where one is protected from its consequences.'},
        {'term': 'Adverse Selection', 'jp': '逆選択', 'desc': '契約前、情報の非対称性により、質の悪い財や相手が選ばれてしまう現象（レモン市場）。', 'desc_en': 'A situation where sellers have information that buyers do not, or vice versa.'},
        {'term': 'Information Asymmetry', 'jp': '情報の非対称性', 'desc': '取引当事者間で持っている情報量に格差がある状態。', 'desc_en': 'A condition in which at least some relevant information is known to some but not all parties involved.'},
        {'term': 'Signaling', 'jp': 'シグナリング', 'desc': '情報を持つ側が、持たない側に情報を信じてもらうためにとる行動（資格取得、配当など）。', 'desc_en': 'The idea that one party credibly conveys some information about itself to another party.'},
        {'term': 'Screening', 'jp': 'スクリーニング', 'desc': '情報を持たない側が、持つ側の私的情報を引き出そうとする行動（保険のメニュー提示など）。', 'desc_en': 'A strategy of combating adverse selection by filtering out false information.'},
        {'term': 'Fixed Cost', 'jp': '固定費', 'desc': '操業度の増減に関わらず一定額発生する原価（家賃、減価償却費など）。', 'desc_en': 'Business costs, such as rent, that are constant whatever the quantity of goods or services produced.'},
        {'term': 'Mixed Cost', 'jp': '準変動費/準固定費', 'desc': '変動費と固定費の両方の性質を持つ原価（基本料金＋従量料金など）。', 'desc_en': 'A cost that contains both a fixed cost component and a variable cost component.'},
        {'term': 'High-Low Method', 'jp': '高低点法', 'desc': '過去のデータの最高点と最低点を用いて、原価を変動費と固定費に分解する簡便法。', 'desc_en': 'A method of attempting to separate out fixed and variable costs given a limited amount of data.'},
        {'term': 'Scatter Plot', 'jp': '散布図法', 'desc': '過去の原価データをグラフにプロットし、目視で傾向線を引いて固変分解する方法。', 'desc_en': 'A graph in which the values of two variables are plotted along two axes.'},
        {'term': 'Regression Analysis', 'jp': '回帰分析', 'desc': '統計的手法（最小二乗法）を用いて、原価と操業度の関係式（回帰直線）を求める方法。最も精度が高い。', 'desc_en': 'A statistical process for estimating the relationships among variables.'},
        {'term': 'Margin of Safety Ratio', 'jp': '安全余裕率', 'desc': '(売上高 - 損益分岐点売上高) ÷ 売上高。経営の安全度を示す。', 'desc_en': 'Indicates how much sales can drop before the business suffers a loss.'},
        {'term': 'Operating Profit', 'jp': '営業利益', 'desc': '本業の収益力。売上総利益 - 販管費。', 'desc_en': 'A profit from business operations (gross profit minus operating expenses) before deduction of interest and taxes.'},
        {'term': 'Cost Center', 'jp': '原価センター', 'desc': '原価の発生のみに責任を持つ責任センター（製造部門など）。', 'desc_en': 'A department or other unit within an organization to which costs may be charged.'},
        {'term': 'Profit Center', 'jp': '利益センター', 'desc': '収益と原価の両方（利益）に責任を持つ責任センター（事業部など）。', 'desc_en': 'A part of an organization with assignable revenues and costs and hence ascertainable profitability.'},
        {'term': 'Investment Center', 'jp': '投資センター', 'desc': '利益だけでなく、投下資本（投資）に対する効率性にも責任を持つ責任センター。', 'desc_en': 'A business unit that can utilize capital to contribute directly to a company\'s profitability.'},
        {'term': 'Management Accounting', 'jp': '管理会計', 'desc': '経営者の意思決定や業績管理のために行われる、企業内部向けの会計。', 'desc_en': 'Accounting used to provide information to people within an organization to aid in decision-making.'},
        {'term': 'Financial Accounting', 'jp': '財務会計', 'desc': '株主や債権者などの外部利害関係者への報告を目的とする会計。', 'desc_en': 'The field of accounting concerned with the summary, analysis and reporting of financial transactions.'},
        {'term': 'Backflush Costing', 'jp': 'バックフラッシュ原価計算', 'desc': '生産完了時点で一括して原価配賦を行う簡便法。JITと親和性が高い。', 'desc_en': 'A costing method where product costs are assigned at the time of completion.'},
        {'term': 'Joint Cost', 'jp': '共通原価', 'desc': '複数の製品が同時に生産される過程で発生し、個別製品に直接追跡できない原価。', 'desc_en': 'Costs incurred up to the split-off point in a joint production process.'},
        {'term': 'By-product', 'jp': '副産物', 'desc': '主製品の生産過程で付随的に得られる価値のある産物。', 'desc_en': 'A secondary product obtained incidentally in addition to the principal product.'},
        {'term': 'Equivalent Units', 'jp': '完成品換算量', 'desc': '仕掛品を完成品ベースに換算した数量。工程別原価計算で使用。', 'desc_en': 'A measure used to convert partially completed units into equivalent completed units.'},
        {'term': 'Weighted-average Process Costing', 'jp': '総合原価計算（総平均法）', 'desc': '期首仕掛品と当期投入を合算し平均単価を算出する工程別原価計算。', 'desc_en': 'A process costing method that averages costs across units.'},
        {'term': 'FIFO Process Costing', 'jp': '総合原価計算（先入先出法）', 'desc': '当期の作業量に基づき、期首仕掛分と当期分を区別して計算する方法。', 'desc_en': 'A process costing method that separates beginning inventory from current production.'},
        {'term': 'Responsibility Accounting', 'jp': '責任会計', 'desc': '組織を責任センターに分け、各責任者の業績を測定・評価する仕組み。', 'desc_en': 'A system where managers are responsible for the costs and revenues they control.'},
        {'term': 'Standard Quantity Variance', 'jp': '数量差異', 'desc': '標準消費量と実際消費量の差に基づく差異。', 'desc_en': 'Variance arising from differences between standard and actual quantities used.'},
        {'term': 'Price Variance', 'jp': '価格差異', 'desc': '標準価格と実際価格の差に基づく差異。', 'desc_en': 'Variance arising from differences between standard and actual prices.'},
        {'term': 'Mix Variance', 'jp': 'ミックス差異', 'desc': '材料や労務の配合比率の相違による差異。', 'desc_en': 'Variance due to differences in the proportion of inputs used.'},
        {'term': 'Yield Variance', 'jp': '歩留差異', 'desc': '投入に対する産出の効率差から生じる差異。', 'desc_en': 'Variance due to differences between actual and expected output.'},
        {'term': 'Activity-Based Management', 'jp': '活動基準管理（ABM）', 'desc': 'ABCの概念を用いて活動の価値を評価し、改善する管理手法。', 'desc_en': 'Using ABC information to improve business processes and profitability.'},
        {'term': 'Life-cycle Costing', 'jp': 'ライフサイクル・コスティング', 'desc': '製品の企画から廃棄までの全期間コストを管理する手法。', 'desc_en': 'Tracking and managing costs across a product’s entire life cycle.'},
        {'term': 'Total Quality Management', 'jp': 'TQM（総合的品質管理）', 'desc': '全社的な品質向上活動によって顧客満足と低コストを実現する管理手法。', 'desc_en': 'A management approach focused on long-term success through customer satisfaction.'},
        {'term': 'Value Engineering', 'jp': 'VE（価値工学）', 'desc': '機能を保ちつつコストを削減する体系的手法。', 'desc_en': 'A method to improve the value of a product by examining function.'},
        {'term': 'Capital Rationing', 'jp': '資本制約下の投資選択', 'desc': '投資資金が制約される中でプロジェクトを選択する意思決定。', 'desc_en': 'Selecting projects when the capital budget is limited.'},
        {'term': 'Post-audit', 'jp': '事後監査（投資）', 'desc': '投資後に実績を検証し、見積りとの乖離原因を分析する手続。', 'desc_en': 'Reviewing outcomes of capital projects to compare with projections.'},
        {'term': 'Sales Mix Variance', 'jp': '製品ミックス差異', 'desc': '想定と異なる販売構成による利益の差異。', 'desc_en': 'Variance due to the difference between actual and budgeted sales mix.'},
        {'term': 'Flexible Manufacturing System', 'jp': 'FMS（フレキシブル生産）', 'desc': '生産ラインの柔軟性を高め、多品種少量生産に対応する仕組み。', 'desc_en': 'A method for producing goods that is flexible for changes.'},
        {'term': 'Throughput', 'jp': 'スループット', 'desc': '売上高から唯一の変動費である材料費を控除した額（TOC）。', 'desc_en': 'Sales minus material cost in TOC-based throughput accounting.'},
        {'term': 'Drum-Buffer-Rope', 'jp': 'DBRスケジューリング', 'desc': '制約工程（ドラム）に合わせたバッファとロープで流れを管理する手法。', 'desc_en': 'A TOC scheduling process using drum, buffer, and rope.'},
        {'term': 'Kaizen Budgeting', 'jp': '改善予算', 'desc': '継続的な改善を織り込んだ予算編成。', 'desc_en': 'Budgeting that incorporates continuous improvements.'},
        {'term': 'Rolling Forecast', 'jp': 'ローリング・フォーキャスト', 'desc': '固定予算に代わり継続的に見通しを更新する計画手法。', 'desc_en': 'A continuously updated forecast that extends beyond the current period.'},
        {'term': 'Benchmark Variance', 'jp': 'ベンチマーク差異', 'desc': '外部ベンチマークと自社実績の差異。', 'desc_en': 'Difference between external benchmarks and internal performance.'},
        {'term': 'Cost of Quality', 'jp': '品質コスト', 'desc': '予防・評価・内部失敗・外部失敗の各コストを体系的に把握する。', 'desc_en': 'Preventive, appraisal, internal failure, and external failure costs.'},
        {'term': 'Theory of Constraints', 'jp': '制約理論（TOC）', 'desc': 'ボトルネックの能力を最大化し全体最適を図る考え方。', 'desc_en': 'A methodology for identifying and managing the bottleneck to improve flow.'},
        {'term': 'Target Profit Analysis', 'jp': '目標利益分析', 'desc': '所要売上高や所要数量を目標利益から逆算する分析。', 'desc_en': 'Determining required sales to achieve a target profit.'},
        {'term': 'Shutdown Decision', 'jp': '操業停止の意思決定', 'desc': '短期的に価格が平均変動費を下回る場合などの停止判断。', 'desc_en': 'Decision to shut down when price falls below average variable cost.'},
        {'term': 'Capacity Utilization', 'jp': '操業度利用率', 'desc': '実際操業度／最大操業度で示す稼働効率。', 'desc_en': 'A measure of how intensively production capacity is used.'},
        {'term': 'Learning Rate', 'jp': '習熟率', 'desc': '累積生産量の倍増に伴う作業時間の逓減割合。', 'desc_en': 'The rate at which time per unit declines as experience increases.'}
    ],
    'Audit': [
        # Existing terms
        {'term': 'Professional Skepticism', 'jp': '職業的懐疑心', 'desc': '常に疑念を持ち、監査証拠を批判的に評価する姿勢。', 'desc_en': 'An attitude that includes a questioning mind and a critical assessment of audit evidence.'},
        {'term': 'Audit Risk', 'jp': '監査リスク', 'desc': '財務諸表に重要な虚偽表示があるにもかかわらず、監査人が不適切な意見を表明するリスク。', 'desc_en': 'The risk that the auditor expresses an inappropriate audit opinion when the financial statements are materially misstated.'},
        {'term': 'Material Misstatement', 'jp': '重要な虚偽表示', 'desc': '財務諸表利用者の判断を誤らせる可能性のある誤りや不正。', 'desc_en': 'An error or fraud in financial statements that is significant enough to impact user decisions.'},
        {'term': 'Internal Control', 'jp': '内部統制', 'desc': '業務の有効性・効率性、財務報告の信頼性などを確保するために組織内に構築されるプロセス。', 'desc_en': 'A process designed to provide reasonable assurance regarding the achievement of objectives.'},
        {'term': 'Substantive Procedures', 'jp': '実証手続', 'desc': '重要な虚偽表示を発見するために、取引や残高の詳細を直接検証する手続。', 'desc_en': 'Audit procedures designed to detect material misstatements at the assertion level.'},
        {'term': 'Significant Deficiency', 'jp': '重要な不備', 'desc': '内部統制の不備のうち、財務諸表の信頼性に重要な影響を及ぼす可能性が高いもの。', 'desc_en': 'A deficiency in internal control that is less severe than a material weakness yet important enough to merit attention.'},
        {'term': 'Key Audit Matters (KAM)', 'jp': '監査上の主要な検討事項', 'desc': '当年度の監査において、職業的専門家として特に重要であると判断した事項。', 'desc_en': 'Those matters that, in the auditor\'s professional judgment, were of most significance in the audit.'},
        {'term': 'Audit Evidence', 'jp': '監査証拠', 'desc': '監査意見の基礎となる結論を導くために監査人が入手した情報。', 'desc_en': 'Information used by the auditor in arriving at the conclusions on which the auditor\'s opinion is based.'},
        {'term': 'Sampling Risk', 'jp': '試査リスク', 'desc': '監査人が母集団の一部（試査）に基づいて結論を出す際に、母集団全体を精査した場合と異なる結論になるリスク。', 'desc_en': 'The risk that the auditor\'s conclusion based on a sample may be different from the conclusion if the entire population were subjected to the same audit procedure.'},
        {'term': 'Management Representation Letter', 'jp': '経営者確認書', 'desc': '経営者が監査人に対して、財務諸表作成責任の履行や情報の完全性などを文書で確認するもの。', 'desc_en': 'A letter from management confirming certain representations made to the auditor.'},
        {'term': 'Subsequent Events', 'jp': '後発事象', 'desc': '決算日後に発生した事象で、次期以降の財政状態や経営成績に影響を及ぼすもの。', 'desc_en': 'Events occurring between the date of the financial statements and the date of the auditor\'s report.'},
        {'term': 'Audit Opinion', 'jp': '監査意見', 'desc': '財務諸表が適正に表示されているかどうかについての監査人の結論。', 'desc_en': 'The conclusion expressed by the auditor regarding the financial statements.'},
        {'term': 'Emphasis of Matter Paragraph', 'jp': '強調事項区分', 'desc': '監査意見には影響しないが、財務諸表利用者の理解のために特に強調すべき事項を記載する区分。', 'desc_en': 'A paragraph included in the auditor\'s report that refers to a matter appropriately presented or disclosed in the financial statements.'},
        {'term': 'Independence', 'jp': '独立性', 'desc': '監査人が被監査会社から精神的・外観的に独立していること。公正不偏な態度の保持。', 'desc_en': 'The state of being objective and not influenced by personal or business relationships.'},
        {'term': 'Fraud Triangle', 'jp': '不正のトライアングル', 'desc': '不正発生の3要素（動機・プレッシャー、機会、正当化）を示すモデル。', 'desc_en': 'A framework designed to explain the reasoning behind a worker\'s decision to commit workplace fraud.'},
        {'term': 'Analytical Procedures', 'jp': '分析的手続', 'desc': '財務データと非財務データの間の相関関係などを分析し、異常な変動を識別する手続。', 'desc_en': 'Evaluations of financial information through analysis of plausible relationships among both financial and non-financial data.'},
        {'term': 'Audit Engagement Letter', 'jp': '監査契約書', 'desc': '監査人と被監査会社との間で交わされる、監査の目的や範囲、責任等を明確にした契約書。', 'desc_en': 'A written agreement between an auditor and a client defining the scope and terms of the audit engagement.'},
        {'term': 'Significant Risk', 'jp': '特別な検討を必要とするリスク', 'desc': '監査人が、監査上の対応として特別な考慮が必要であると判断した、重要な虚偽表示リスク。', 'desc_en': 'An identified and assessed risk of material misstatement that, in the auditor\'s judgment, requires special audit consideration.'},
        {'term': 'Performance Materiality', 'jp': '手続実施上の重要性', 'desc': '未発見の虚偽表示が財務諸表全体としての重要性を超えないようにするために設定される、重要性より低い金額。', 'desc_en': 'The amount set by the auditor at less than materiality for the financial statements as a whole to reduce to an appropriately low level the probability that the aggregate of uncorrected and undetected misstatements exceeds materiality.'},
        {'term': 'Walkthrough', 'jp': 'ウォークスルー', 'desc': '取引の開始から記帳、報告に至るまでの一連のプロセスを追跡し、内部統制の整備状況を確かめる手続。', 'desc_en': 'Tracing a transaction step-by-step through the accounting system from its inception to the final disposition.'},
        {'term': 'External Confirmation', 'jp': '確認', 'desc': '監査人が、取引先や銀行などの第三者から直接、書面による回答を入手する手続。', 'desc_en': 'Audit evidence obtained as a direct written response to the auditor from a third party.'},
        # New Terms
        {'term': 'Audit Plan', 'jp': '監査計画', 'desc': '監査を効率的かつ効果的に実施するために、監査の範囲、時期、方向性を定めた計画。', 'desc_en': 'The specific guidelines to be followed when conducting an audit.'},
        {'term': 'Audit Strategy', 'jp': '監査戦略', 'desc': '監査計画の全体的な方針。監査の範囲、実施時期、方向性を設定し、監査計画の策定を指針付ける。', 'desc_en': 'The overall approach to the audit that sets the scope, timing, and direction.'},
        {'term': 'Inherent Risk', 'jp': '固有リスク', 'desc': '内部統制が存在しないと仮定した場合に、重要な虚偽表示が発生する可能性。', 'desc_en': 'The susceptibility of an assertion to a misstatement that could be material, assuming no related internal controls.'},
        {'term': 'Control Risk', 'jp': '統制リスク', 'desc': '企業の内部統制によって、重要な虚偽表示が防止または発見・是正されないリスク。', 'desc_en': 'The risk that a material misstatement will not be prevented or detected on a timely basis by the entity\'s internal control.'},
        {'term': 'Detection Risk', 'jp': '発見リスク', 'desc': '監査人が実施した手続によっても、重要な虚偽表示を発見できないリスク。監査人がコントロールできる唯一のリスク。', 'desc_en': 'The risk that the procedures performed by the auditor will not detect a misstatement that exists.'},
        {'term': 'Audit Risk Model', 'jp': '監査リスクモデル', 'desc': '監査リスク ＝ 固有リスク × 統制リスク × 発見リスク という関係式。', 'desc_en': 'A model used to manage the risks associated with an audit.'},
        {'term': 'Tolerable Misstatement', 'jp': '許容誤謬', 'desc': '監査サンプリングにおいて、監査人が受け入れ可能な最大の誤りの金額。', 'desc_en': 'The application of performance materiality to a particular sampling procedure.'},
        {'term': 'Sufficiency', 'jp': '十分性（監査証拠の）', 'desc': '監査証拠の量的な尺度。リスク評価や証拠の質に依存する。', 'desc_en': 'The measure of the quantity of audit evidence.'},
        {'term': 'Appropriateness', 'jp': '適切性（監査証拠の）', 'desc': '監査証拠の質的な尺度。関連性と信頼性からなる。', 'desc_en': 'The measure of the quality of audit evidence (relevance and reliability).'},
        {'term': 'Inspection', 'jp': '閲覧・実査', 'desc': '記録や文書を調べたり（閲覧）、資産の実在を物理的に確かめたり（実査）する手続。', 'desc_en': 'Examining records or documents, or physical examination of an asset.'},
        {'term': 'Observation', 'jp': '立会', 'desc': '他者が行っているプロセスや手続を監査人が見ること（棚卸立会など）。', 'desc_en': 'Looking at a process or procedure being performed by others.'},
        {'term': 'Inquiry', 'jp': '質問', 'desc': '企業内外の知識を有する者に情報を求め、回答を得ること。', 'desc_en': 'Seeking information of knowledgeable persons, both financial and non-financial, within the entity or outside.'},
        {'term': 'Recalculation', 'jp': '再計算', 'desc': '文書や記録の数学的な正確性を監査人が自ら計算して確かめること。', 'desc_en': 'Checking the mathematical accuracy of documents or records.'},
        {'term': 'Reperformance', 'jp': '再実施', 'desc': '企業の内部統制の一部として行われた手続を、監査人が独立して行うこと。', 'desc_en': 'Independent execution by the auditor of procedures or controls that were originally performed as part of the entity\'s internal control.'},
        {'term': 'Test of Controls', 'jp': '運用評価手続', 'desc': '内部統制が有効にデザインされ、運用されているかを検証する手続。', 'desc_en': 'An audit procedure to test the effectiveness of a control used by a client entity.'},
        {'term': 'Audit Sampling', 'jp': '監査サンプリング', 'desc': '母集団の100%未満の項目に監査手続を適用し、母集団全体についての結論を導く手法。', 'desc_en': 'The application of audit procedures to less than 100% of items within a population.'},
        {'term': 'Stratification', 'jp': '層別', 'desc': '母集団を類似した特性を持つ部分母集団（層）に分割すること。サンプリング効率を高める。', 'desc_en': 'The process of dividing a population into subpopulations, each of which is a group of sampling units which have similar characteristics.'},
        {'term': 'Audit Documentation', 'jp': '監査調書', 'desc': '実施した監査手続、入手した監査証拠、到達した結論の記録。', 'desc_en': 'The record of audit procedures performed, relevant audit evidence obtained, and conclusions the auditor reached.'},
        {'term': 'Working Papers', 'jp': 'ワーキング・ペーパー', 'desc': '監査調書の別名。', 'desc_en': 'Another term for audit documentation.'},
        {'term': 'Related Parties', 'jp': '関連当事者', 'desc': '親会社、子会社、主要株主、役員など、企業と密接な関係にある者。取引の透明性が重要。', 'desc_en': 'A person or entity that is related to the entity that is preparing its financial statements.'},
        {'term': 'Opening Balances', 'jp': '期首残高', 'desc': '当期の期首に存在する勘定残高。前期末の残高と一致している必要がある。', 'desc_en': 'Account balances that exist at the beginning of the period.'},
        {'term': 'Accounting Estimates', 'jp': '会計上の見積り', 'desc': '貸倒引当金や公正価値など、正確な測定が困難な金額について、利用可能な情報に基づいて近似値を算出すること。', 'desc_en': 'An approximation of a monetary amount in the absence of a precise means of measurement.'},
        {'term': 'Group Audit', 'jp': 'グループ監査', 'desc': '複数の構成単位（子会社など）を持つ企業の連結財務諸表に対する監査。', 'desc_en': 'The audit of group financial statements.'},
        {'term': 'Component Auditor', 'jp': '構成単位の監査人', 'desc': 'グループ監査において、特定の子会社などの監査を担当する別の監査人。', 'desc_en': 'An auditor who, at the request of the group engagement team, performs work on financial information related to a component.'},
        {'term': 'Review Engagement', 'jp': 'レビュー業務', 'desc': '監査よりも限定的な保証（消極的保証）を提供する業務。質問や分析的手続が中心。', 'desc_en': 'An engagement designed to provide limited assurance.'},
        {'term': 'Code of Ethics', 'jp': '倫理規則', 'desc': '公認会計士が遵守すべき行動規範（誠実性、公正性など）。', 'desc_en': 'Principles and expectations governing the behavior of individuals and organizations.'},
        {'term': 'Quality Control', 'jp': '品質管理', 'desc': '監査事務所が業務の質を維持するために設ける方針と手続。', 'desc_en': 'A process by which entities review the quality of all factors involved in production.'},
        {'term': 'EQCR (Engagement Quality Control Review)', 'jp': '審査', 'desc': '監査報告書発行前に、監査チーム外の客観的な審査担当者が監査の質を確認するプロセス。', 'desc_en': 'A process designed to provide an objective evaluation, on or before the date of the report, of the significant judgments the engagement team made.'},
        {'term': 'Unqualified Opinion', 'jp': '無限定適正意見', 'desc': '財務諸表がすべての重要な点において適正に表示されているという意見。', 'desc_en': 'An opinion that financial statements are presented fairly in all material respects.'},
        {'term': 'Qualified Opinion', 'jp': '限定付適正意見', 'desc': '一部に重要な虚偽表示や範囲の制限があるが、全体としては適正であるという意見（除外事項付）。', 'desc_en': 'An opinion that, except for the effects of the matter to which the qualification relates, the financial statements are presented fairly.'},
        {'term': 'Adverse Opinion', 'jp': '不適正意見', 'desc': '財務諸表が全体として適正に表示されていないという意見。', 'desc_en': 'An opinion that the financial statements are not presented fairly.'},
        {'term': 'Disclaimer of Opinion', 'jp': '意見不表明', 'desc': '監査証拠が十分に手に入らず、意見を表明できない場合。', 'desc_en': 'A statement that the auditor does not express an opinion on the financial statements.'},
        {'term': 'Other Matter Paragraph', 'jp': 'その他の事項区分', 'desc': '財務諸表には記載されていないが、監査や監査人の責任を理解するために重要な事項。', 'desc_en': 'A paragraph included in the auditor\'s report that refers to a matter other than those presented or disclosed in the financial statements.'},
        {'term': 'Misstatement', 'jp': '虚偽表示', 'desc': '財務諸表の金額、分類、表示、開示が、あるべき姿と異なっていること。', 'desc_en': 'A difference between the amount, classification, presentation, or disclosure of a reported financial statement item and the amount, classification, presentation, or disclosure that is required.'},
        {'term': 'Error', 'jp': '誤謬', 'desc': '意図的でない虚偽表示（計算ミス、事実の見落としなど）。', 'desc_en': 'An unintentional misstatement in financial statements.'},
        {'term': 'Fraud', 'jp': '不正', 'desc': '不当または違法な利益を得るための、意図的な虚偽表示や資産の流用。', 'desc_en': 'An intentional act involving the use of deception to obtain an unjust or illegal advantage.'},
        {'term': 'Fraud Risk Factors', 'jp': '不正リスク要因', 'desc': '不正のトライアングル（動機、機会、正当化）を示す事象や状況。', 'desc_en': 'Events or conditions that indicate an incentive or pressure to commit fraud or provide an opportunity to commit fraud.'},
        {'term': 'Misappropriation of Assets', 'jp': '資産の流用', 'desc': '会社の資産を盗むこと（横領など）。', 'desc_en': 'Theft of an entity\'s assets.'},
        {'term': 'Fraudulent Financial Reporting', 'jp': '粉飾決算', 'desc': '財務諸表の利用者を欺くために、意図的に数値を操作すること。', 'desc_en': 'Intentional misstatements or omissions of amounts or disclosures in financial statements to deceive financial statement users.'},
        {'term': 'Assertions', 'jp': 'アサーション（経営者の主張）', 'desc': '財務諸表に含まれる情報が正しいという経営者の主張（実在性、網羅性、評価など）。', 'desc_en': 'Representations by management regarding the recognition, measurement, presentation, and disclosure of information in the financial statements.'},
        {'term': 'Existence', 'jp': '実在性', 'desc': '資産や負債が実際に存在していること。', 'desc_en': 'Assets, liabilities, and equity interests exist.'},
        {'term': 'Completeness', 'jp': '網羅性', 'desc': '計上すべき取引や資産がすべて記録されていること。', 'desc_en': 'All transactions and events that should have been recorded have been recorded.'},
        {'term': 'Valuation', 'jp': '評価', 'desc': '資産や負債が適切な金額で記録されていること。', 'desc_en': 'Assets, liabilities, and equity interests are included in the financial statements at appropriate amounts.'},
        {'term': 'Rights and Obligations', 'jp': '権利と義務', 'desc': '会社が資産の権利を持ち、負債の義務を負っていること。', 'desc_en': 'The entity holds or controls the rights to assets, and liabilities are the obligations of the entity.'},
        {'term': 'Cutoff', 'jp': '期間帰属', 'desc': '取引が正しい会計期間に記録されていること。', 'desc_en': 'Transactions and events have been recorded in the correct accounting period.'},
        {'term': 'Accuracy', 'jp': '正確性', 'desc': '金額やその他のデータが正しく記録されていること。', 'desc_en': 'Amounts and other data relating to recorded transactions and events have been recorded appropriately.'},
        {'term': 'Classification', 'jp': '分類', 'desc': '取引が適切な勘定科目に記録されていること。', 'desc_en': 'Transactions and events have been recorded in the proper accounts.'},
        {'term': 'Presentation', 'jp': '表示', 'desc': '財務諸表の情報が適切に分類され、明瞭に記述されていること。', 'desc_en': 'Transactions and events are appropriately aggregated or disaggregated and clearly described.'}
    ,        {'term': 'Risk Assessment Procedures', 'jp': 'リスク評価手続', 'desc': '企業理解、分析的手続、質問などを通じて重要な虚偽表示リスクを識別・評価する。', 'desc_en': 'Procedures to identify and assess risks of material misstatement.'},
        {'term': 'Overall Materiality', 'jp': '全体重要性', 'desc': '財務諸表全体に対して設定される重要性水準。', 'desc_en': 'Materiality level for the financial statements as a whole.'},
        {'term': 'Component Materiality', 'jp': '構成単位重要性', 'desc': 'グループ監査で各構成単位に設定される重要性。', 'desc_en': 'Materiality allocated to components in a group audit.'},
        {'term': 'Aggregation of Misstatements', 'jp': '虚偽表示の集計', 'desc': '発見された虚偽表示を集計し、重要性と比較して評価する。', 'desc_en': 'Accumulating misstatements and evaluating against materiality.'},
        {'term': 'Communication with TCWG', 'jp': 'ガバナンス担当者とのコミュニケーション', 'desc': '監査範囲、重要な所見、内部統制不備等を取締役会等へ報告。', 'desc_en': 'Communicating significant audit matters to those charged with governance.'},
        {'term': 'Going Concern Assessment', 'jp': '継続企業の前提の評価', 'desc': '企業の継続性に疑義があるかどうかを評価し、必要に応じて追加手続を実施。', 'desc_en': 'Assessing whether there is substantial doubt about going concern.'},
        {'term': 'Engagement Acceptance', 'jp': '業務受嘱', 'desc': '独立性、専門能力、倫理要件を確認し、業務受嘱の可否を判断。', 'desc_en': 'Determining whether to accept or continue an audit engagement.'},
        {'term': 'Independence Threats', 'jp': '独立性脅威', 'desc': '自己利害、自己査定、擁護、密接、威圧の各脅威と対応措置。', 'desc_en': 'Self-interest, self-review, advocacy, familiarity, and intimidation threats.'},
        {'term': 'IT General Controls', 'jp': 'IT全般統制（ITGC）', 'desc': 'アクセス管理、変更管理、運用管理等、IT環境における統制。', 'desc_en': 'Controls over the IT environment such as access and change management.'},
        {'term': 'CAATs', 'jp': 'コンピュータ利用監査技法', 'desc': 'データ抽出や再計算をシステムで実施する監査技法。', 'desc_en': 'Computer-assisted audit techniques for data analysis and testing.'},
        {'term': 'Significant Accounts', 'jp': '重要な勘定', 'desc': '虚偽表示リスクが高い勘定・開示を識別し、アサーションと対応付ける。', 'desc_en': 'Accounts and disclosures with higher risk of misstatement.'},
        {'term': 'Monetary Unit Sampling', 'jp': '金額単位サンプリング（MUS）', 'desc': '金額をサンプリング単位とし、高額項目の抽出確率を高める手法。', 'desc_en': 'Probability-proportional-to-size sampling technique.'},
        {'term': 'Random Sampling', 'jp': '無作為抽出', 'desc': '母集団の各要素に均等な選択確率を与える抽出方法。', 'desc_en': 'Selecting sample items so that all have an equal chance of being chosen.'},
        {'term': 'Haphazard Sampling', 'jp': '恣意抽出', 'desc': '規則性なく任意に項目を選ぶ方法（統計的根拠は弱い）。', 'desc_en': 'Selecting items without conscious bias but without randomization.'},
        {'term': 'Tolerable Deviation Rate', 'jp': '許容逸脱率', 'desc': '統制テストで許容できる内部統制の逸脱率。', 'desc_en': 'The maximum rate of deviation from a control that the auditor is willing to accept.'},
        {'term': 'Expected Deviation Rate', 'jp': '期待逸脱率', 'desc': '統制の運用評価において予想される逸脱率。', 'desc_en': 'The rate of deviation the auditor expects to find in a population.'},
        {'term': 'Dual-purpose Test', 'jp': '二重目的テスト', 'desc': '同一サンプルで統制テストと実証手続を兼ねるテスト。', 'desc_en': 'A test that serves as both a test of controls and a substantive test.'},
        {'term': 'Adjusting Events', 'jp': '修正再表示事象', 'desc': '決算日後であっても、決算日時点の状況の証拠となる後発事象。', 'desc_en': 'Events after the reporting period that provide evidence of conditions at the end of the reporting period.'},
        {'term': 'Non-adjusting Events', 'jp': '非修正事象', 'desc': '決算日後に発生した新たな状況に関する後発事象。', 'desc_en': 'Events indicative of conditions that arose after the reporting period.'},
        {'term': 'Deficiency Communication', 'jp': '内部統制不備のコミュニケーション', 'desc': '重要な不備や重大な不備を経営者・ガバナンス担当者に報告。', 'desc_en': 'Communicating significant deficiencies and material weaknesses.'},
        {'term': 'Completion Checklist', 'jp': '監査完了チェックリスト', 'desc': '報告書発行前に必要手続が完了していることを確認するリスト。', 'desc_en': 'Checklist to ensure all required procedures are complete before reporting.'},
        {'term': 'Roll-forward Procedures', 'jp': 'ロールフォワード手続', 'desc': '期中に実施したテスト結果を期末まで延長する手続。', 'desc_en': 'Updating interim testing to year-end.'},
        {'term': 'Interim Testing', 'jp': '期中テスト', 'desc': '期末前に実施する監査手続で効率化を図る。', 'desc_en': 'Performing audit procedures before year-end to improve efficiency.'},
        {'term': 'Group Instructions', 'jp': 'グループ監査指示書', 'desc': 'グループ監査チームが構成単位監査人に発出する指示。', 'desc_en': 'Instructions sent by group auditors to component auditors.'},
        {'term': 'Component Communication', 'jp': '構成単位とのコミュニケーション', 'desc': '重要なリスク、重要性、報告事項等を相互に共有。', 'desc_en': 'Two-way communication between group and component auditors.'},
        {'term': 'Revenue Recognition Risk', 'jp': '収益認識リスク', 'desc': '不正リスクが高いとされる領域として重点的に検討。', 'desc_en': 'Presumed significant risk often requiring special consideration.'},
        {'term': 'Cut-off Testing', 'jp': 'カットオフテスト', 'desc': '収益費用の期間帰属を確認するため、期末前後の取引を検証。', 'desc_en': 'Testing transactions around year-end to ensure proper period recognition.'},
        {'term': 'Subsequent Receipt', 'jp': '期末後入金の確認', 'desc': '売掛金の実在性確認として、期末後の入金を検証。', 'desc_en': 'Verifying subsequent cash receipts to test existence/valuation of receivables.'},
        {'term': 'Physical Inventory Observation', 'jp': '棚卸立会（実地棚卸）', 'desc': '在庫の存在・状態を確認するための立会。', 'desc_en': 'Observing the client’s physical inventory count.'},
        {'term': 'Bank Reconciliation Testing', 'jp': '銀行勘定調整表のテスト', 'desc': '銀行残高証明との突合や未達項目の妥当性評価。', 'desc_en': 'Testing the reconciliation of book to bank balances.'},
        {'term': 'Law and Regulations', 'jp': '法令遵守の検討', 'desc': '財務報告に影響を与える法令違反の兆候を検討。', 'desc_en': 'Considering compliance with laws and regulations affecting financial statements.'},
        {'term': 'Management Bias Indicators', 'jp': '経営者バイアスの兆候', 'desc': '見積りや開示における恣意性の兆候を検討。', 'desc_en': 'Indicators of possible management bias in estimates and disclosures.'},
        {'term': 'Sampling Frame', 'jp': 'サンプリング母集団', 'desc': '監査サンプルを抽出する対象の全体集合。', 'desc_en': 'The population from which a sample is drawn.'},
        {'term': 'Population Stratification', 'jp': '母集団の層別化', 'desc': '金額などで層別し、サンプリング効率を高める。', 'desc_en': 'Dividing a population into subgroups for sampling efficiency.'}
    ],
    'Company': [
        # Existing terms
        {'term': 'Fiduciary Duty', 'jp': '受託者責任', 'desc': '取締役などが会社や株主のために忠実に職務を遂行する義務（善管注意義務・忠実義務）。', 'desc_en': 'The legal duty to act solely in another party\'s interests.'},
        {'term': 'Shareholder Derivative Suit', 'jp': '株主代表訴訟', 'desc': '会社が取締役の責任を追及しない場合に、株主が会社に代わって提起する訴訟。', 'desc_en': 'A lawsuit brought by a shareholder on behalf of a corporation against a third party.'},
        {'term': 'Business Judgment Rule', 'jp': '経営判断の原則', 'desc': '取締役の経営判断が合理的で誠実に行われた場合、結果的に損害が生じても責任を問われない原則。', 'desc_en': 'A presumption that directors\' decisions are based on informed and good faith judgment.'},
        {'term': 'Authorized Shares', 'jp': '発行可能株式総数', 'desc': '定款で定められた、会社が発行することができる株式の上限数。', 'desc_en': 'The maximum number of shares that a corporation is legally permitted to issue.'},
        {'term': 'Treasury Stock', 'jp': '自己株式', 'desc': '会社が保有する自社の株式。議決権や配当請求権はない。', 'desc_en': 'Stock which is bought back by the issuing company.'},
        {'term': 'Articles of Incorporation', 'jp': '定款', 'desc': '会社の目的、商号、本店所在地などの基本規則を定めた根本規則。', 'desc_en': 'The primary rules governing the management of a corporation.'},
        {'term': 'Board of Directors', 'jp': '取締役会', 'desc': '業務執行の決定や取締役の職務執行の監督を行う機関。', 'desc_en': 'An elected group of individuals that represent shareholders.'},
        {'term': 'Statutory Auditor', 'jp': '監査役', 'desc': '取締役の職務執行や会計を監査する機関。', 'desc_en': 'An official responsible for checking the accuracy of business records.'},
        {'term': 'General Meeting of Shareholders', 'jp': '株主総会', 'desc': '株式会社の最高意思決定機関。株主で構成される。', 'desc_en': 'The highest decision-making body of a company.'},
        {'term': 'Corporate Governance', 'jp': 'コーポレート・ガバナンス', 'desc': '企業経営を規律するための仕組み。企業統治。', 'desc_en': 'The system of rules, practices, and processes by which a firm is directed and controlled.'},
        {'term': 'Stock Option', 'jp': 'ストック・オプション', 'desc': '自社株をあらかじめ決められた価格で購入できる権利。役員や従業員へのインセンティブ。', 'desc_en': 'A privilege that gives the buyer the right to buy or sell stock at an agreed price.'},
        {'term': 'Mergers and Acquisitions (M&A)', 'jp': 'M&A（合併・買収）', 'desc': '企業の合併や買収の総称。組織再編行為を含む。', 'desc_en': 'The consolidation of companies or assets through various financial transactions.'},
        {'term': 'Audit & Supervisory Committee', 'jp': '監査等委員会', 'desc': '取締役会の中に設置される委員会で、取締役の職務執行の監査等を担う（監査等委員会設置会社）。', 'desc_en': 'A committee consisting of directors that audits the execution of duties by directors.'},
        {'term': 'Nomination Committee', 'jp': '指名委員会', 'desc': '株主総会に提出する取締役の選任・解任に関する議案の内容を決定する委員会（指名委員会等設置会社）。', 'desc_en': 'A committee that decides on the content of proposals regarding the election and dismissal of directors to be submitted to the shareholders meeting.'},
        {'term': 'Conflict of Interest', 'jp': '利益相反', 'desc': '取締役自身の利益と会社の利益が対立する状況。このような取引には取締役会の承認が必要。', 'desc_en': 'A situation in which a person or organization is involved in multiple interests, financial or otherwise, and serving one interest could involve working against another.'},
        {'term': 'Minority Shareholder Rights', 'jp': '少数株主権', 'desc': '一定の株式数や比率を持つ株主のみが行使できる権利（株主提案権、帳簿閲覧権など）。', 'desc_en': 'Rights held by shareholders who own a small percentage of the company\'s shares.'},
        {'term': 'Public Notice', 'jp': '公告', 'desc': '会社が合併や減資などの重要な決定を行った際に、債権者や株主に対して広く知らせること。', 'desc_en': 'A notice given to the public regarding certain types of legal proceedings.'},
        # New Terms
        {'term': 'Corporation', 'jp': '株式会社', 'desc': '株式を発行して資金を調達し、株主の出資を資本とする会社形態。', 'desc_en': 'A legal entity that is separate and distinct from its owners.'},
        {'term': 'Legal Personality', 'jp': '法人格', 'desc': '法律上、人と同じように権利・義務の主体となることができる資格。', 'desc_en': 'The quality of being a person in the eye of the law.'},
        {'term': 'Limited Liability', 'jp': '有限責任', 'desc': '株主の責任が出資額の範囲内に限定されること。会社の債務を個人として負わない。', 'desc_en': 'A person\'s financial liability is limited to a fixed sum, most commonly the value of a person\'s investment in a company.'},
        {'term': 'Piercing the Corporate Veil', 'jp': '法人格否認の法理', 'desc': '法人格が形骸化していたり、濫用されている場合に、背後の社員（株主）に責任を問う法理。', 'desc_en': 'A legal decision to treat the rights or duties of a corporation as the rights or liabilities of its shareholders.'},
        {'term': 'Promoter', 'jp': '発起人', 'desc': '会社の設立を企画し、定款に署名した者。', 'desc_en': 'A person who solicits people to invest money in a corporation.'},
        {'term': 'Bylaws', 'jp': '社内規則', 'desc': '定款に基づき、会社の運営に関する詳細を定めた規則。', 'desc_en': 'A rule made by a company or society to control the actions of its members.'},
        {'term': 'Common Stock', 'jp': '普通株式', 'desc': '特別な権利や制限が付されていない標準的な株式。', 'desc_en': 'Shares entitling their holder to dividends that vary in amount and may even be missed, depending on the fortunes of the company.'},
        {'term': 'Preferred Stock', 'jp': '優先株式', 'desc': '配当や残余財産分配において、普通株よりも優先される株式。議決権がないことが多い。', 'desc_en': 'Stock that entitles the holder to a fixed dividend, whose payment takes priority over that of common-stock dividends.'},
        {'term': 'Class Shares', 'jp': '種類株式', 'desc': '権利内容が異なる複数の種類の株式（議決権制限株式、拒否権付株式など）。', 'desc_en': 'Different types of shares issued by a company, having different rights.'},
        {'term': 'Stock Split', 'jp': '株式分割', 'desc': '1株を複数の株式に分割すること。株価を引き下げ、流動性を高める効果がある。', 'desc_en': 'An issue of new shares in a company to existing shareholders in proportion to their current holdings.'},
        {'term': 'Reverse Stock Split', 'jp': '株式併合', 'desc': '複数の株式を1株にまとめること。発行済株式数を減らすために行われる。', 'desc_en': 'A reduction in the number of a company\'s traded shares that results in an increase in the par value or earnings per share.'},
        {'term': 'Unit Share System', 'jp': '単元株制度', 'desc': '一定数（例：100株）を1単元とし、1単元につき1個の議決権を認める制度。', 'desc_en': 'A system where a specified number of shares constitutes one unit for voting purposes.'},
        {'term': 'Voting Rights', 'jp': '議決権', 'desc': '株主総会の決議に参加し、票を投じる権利。', 'desc_en': 'The right of a stockholder to vote on matters of corporate policy.'},
        {'term': 'Dividend', 'jp': '配当', 'desc': '会社が獲得した利益の一部を株主に分配すること。', 'desc_en': 'A sum of money paid regularly by a company to its shareholders out of its profits.'},
        {'term': 'Surplus', 'jp': '剰余金', 'desc': '純資産額から資本金や準備金を控除した額。配当原資となる。', 'desc_en': 'An amount of something left over when requirements have been met.'},
        {'term': 'Capital Reserve', 'jp': '資本準備金', 'desc': '株主からの払込金のうち、資本金に組み入れなかった部分。', 'desc_en': 'A type of account on a municipality\'s or company\'s balance sheet that is reserved for long-term capital investment projects or any other large and anticipated expense.'},
        {'term': 'Distributable Amount', 'jp': '分配可能額', 'desc': '会社法上、株主に配当することができる上限額。', 'desc_en': 'The maximum amount that a company can distribute to shareholders as dividends.'},
        {'term': 'Ordinary Resolution', 'jp': '普通決議', 'desc': '出席株主の議決権の過半数で可決される決議（取締役の選任など）。', 'desc_en': 'A resolution passed by a simple majority.'},
        {'term': 'Special Resolution', 'jp': '特別決議', 'desc': '出席株主の議決権の3分の2以上で可決される決議（定款変更、合併など）。', 'desc_en': 'A resolution that requires a higher majority (usually 2/3) to pass.'},
        {'term': 'Representative Director', 'jp': '代表取締役', 'desc': '会社を代表し、業務を執行する権限を持つ取締役。', 'desc_en': 'A director who has the authority to represent the company.'},
        {'term': 'Executive Officer', 'jp': '執行役', 'desc': '指名委員会等設置会社において、業務執行を担う役員（取締役とは別）。', 'desc_en': 'An officer who is responsible for the management of the company.'},
        {'term': 'Accounting Auditor', 'jp': '会計監査人', 'desc': '会社の計算書類等を監査する外部の専門家（公認会計士または監査法人）。', 'desc_en': 'An external professional who audits the company\'s financial statements.'},
        {'term': 'Officers\' Liability', 'jp': '役員等の責任', 'desc': '任務懈怠により会社や第三者に損害を与えた場合に負う損害賠償責任。', 'desc_en': 'Liability of directors and officers for damages caused by their negligence.'},
        {'term': 'Negligence', 'jp': '過失', 'desc': '注意義務違反。不注意。', 'desc_en': 'Failure to take proper care in doing something.'},
        {'term': 'Gross Negligence', 'jp': '重過失', 'desc': '著しい不注意。ほとんど故意に近い過失。', 'desc_en': 'A lack of care that demonstrates reckless disregard for the safety or lives of others.'},
        {'term': 'Duty of Care', 'jp': '善管注意義務', 'desc': '善良な管理者の注意をもって職務を行う義務。', 'desc_en': 'The legal obligation to act with care and watchfulness.'},
        {'term': 'Duty of Loyalty', 'jp': '忠実義務', 'desc': '会社のために忠実に職務を行う義務。自己の利益を優先してはならない。', 'desc_en': 'The duty to act in the best interest of the company.'},
        {'term': 'Self-dealing', 'jp': '自己取引', 'desc': '取締役が自分自身と会社との間で取引を行うこと。利益相反取引の一つ。', 'desc_en': 'A transaction where a fiduciary acts in their own best interest in a transaction involving the fiduciary\'s clients.'},
        {'term': 'Competitive Transaction', 'jp': '競業取引', 'desc': '取締役が会社の事業と競合する取引を行うこと。承認が必要。', 'desc_en': 'A transaction by a director that competes with the company\'s business.'},
        {'term': 'Board Minutes', 'jp': '議事録', 'desc': '取締役会や株主総会の経過と結果を記録した文書。', 'desc_en': 'The written record of a meeting.'},
        {'term': 'Disclosure', 'jp': '開示', 'desc': '企業の経営内容や財務状況を一般に公開すること。', 'desc_en': 'The act of making new or secret information known.'},
        {'term': 'Commercial Registration', 'jp': '商業登記', 'desc': '会社に関する重要事項（商号、役員など）を法務局の登記簿に記載し、公示する制度。', 'desc_en': 'A public record of information about companies.'},
        {'term': 'Stewardship Code', 'jp': 'スチュワードシップ・コード', 'desc': '機関投資家が投資先企業との対話を通じて、企業価値向上を促すための行動原則。', 'desc_en': 'Principles for responsible institutional investors.'},
        {'term': 'Merger', 'jp': '合併', 'desc': '2つ以上の会社が契約により1つの会社になること。', 'desc_en': 'The combination of two or more companies into a single firm.'},
        {'term': 'Absorption-type Merger', 'jp': '吸収合併', 'desc': 'ある会社が他の会社を吸収し、吸収される会社は消滅する形態。', 'desc_en': 'A merger where one company absorbs another.'},
        {'term': 'Consolidation-type Merger', 'jp': '新設合併', 'desc': '全ての当事会社が消滅し、新しい会社を設立する形態。', 'desc_en': 'A merger where a new company is created and the original companies cease to exist.'},
        {'term': 'Company Split', 'jp': '会社分割', 'desc': '事業の一部または全部を他の会社に承継させること。', 'desc_en': 'Splitting a company\'s business into different entities.'},
        {'term': 'Share Exchange', 'jp': '株式交換', 'desc': 'ある会社が他の会社の株式を全て取得し、完全親会社となること。', 'desc_en': 'A method of making a company a wholly owned subsidiary.'},
        {'term': 'Share Transfer', 'jp': '株式移転', 'desc': '1つ以上の会社が全株式を新設会社に移転し、その完全子会社となること（持株会社設立など）。', 'desc_en': 'Establishing a new parent company by transferring shares.'},
        {'term': 'Business Transfer', 'jp': '事業譲渡', 'desc': '会社の事業の一部または全部を契約により他社に譲渡すること。', 'desc_en': 'Transferring a part or all of a business to another entity.'},
        {'term': 'Dissolution', 'jp': '解散', 'desc': '会社の法人格を消滅させるための法的手続きの開始。', 'desc_en': 'The closing down or dismissal of an assembly, partnership, or official body.'},
        {'term': 'Liquidation', 'jp': '清算', 'desc': '解散した会社の財産関係を整理し、残余財産を株主に分配する手続き。', 'desc_en': 'The process of bringing a business to an end and distributing its assets.'},
        {'term': 'Bankruptcy', 'jp': '破産', 'desc': '支払不能に陥った会社が、裁判所の監督下で財産を清算する手続き。', 'desc_en': 'A legal proceeding involving a person or business that is unable to repay their outstanding debts.'},
        {'term': 'Civil Rehabilitation', 'jp': '民事再生', 'desc': '経営破綻した会社が、経営陣を維持したまま再建を目指す手続き。', 'desc_en': 'A rehabilitation procedure allowing the debtor to continue business.'},
        {'term': 'Corporate Reorganization', 'jp': '会社更生', 'desc': '大規模な株式会社を対象とした、裁判所選任の管財人による厳格な再建手続き。', 'desc_en': 'A reorganization procedure for large stock companies.'},
        {'term': 'Golden Share', 'jp': '拒否権付種類株式（黄金株）', 'desc': '株主総会の決議事項に対して拒否権を行使できる株式。買収防衛策などに使われる。', 'desc_en': 'A share that gives its holder veto power over changes to the company\'s charter.'},
        {'term': 'Poison Pill', 'jp': 'ポイズンピル（買収防衛策）', 'desc': '敵対的買収者が現れた際に、新株予約権などを発行して買収者の持株比率を低下させる防衛策。', 'desc_en': 'A tactic used by a company threatened with an unwelcome takeover bid to make itself unattractive to the bidder.'},
        {'term': 'Compliance', 'jp': 'コンプライアンス', 'desc': '法令遵守。企業が法律や社会規範を守って活動すること。', 'desc_en': 'The action or fact of complying with a wish or command.'},
        {'term': 'Whistleblowing', 'jp': '内部通報', 'desc': '組織内の不正行為を、内部の窓口や外部機関に通報すること。公益通報者保護法で保護される。', 'desc_en': 'The act of telling the authorities or the public that the organization you work for is doing something immoral or illegal.'},
        {'term': 'Large Company', 'jp': '大会社', 'desc': '資本金5億円以上または負債総額200億円以上の株式会社。', 'desc_en': 'A stock company meeting large company thresholds under the Companies Act.'},
        {'term': 'Public Company', 'jp': '公開会社', 'desc': '株式の譲渡制限を設けていない会社。', 'desc_en': 'A company that does not restrict transfer of its shares.'},
        {'term': 'Close Company', 'jp': '非公開会社', 'desc': '株式の譲渡に会社の承認が必要な会社。', 'desc_en': 'A company with restrictions on share transfers.'},
        {'term': 'Transfer Restriction', 'jp': '譲渡制限', 'desc': '株式の譲渡に会社の承認を要する定款規定。', 'desc_en': 'Articles requiring company approval to transfer shares.'},
        {'term': 'Shareholder Registry', 'jp': '株主名簿', 'desc': '株主の氏名・住所・保有株式数等を記載した名簿。', 'desc_en': 'A register of shareholders and their holdings.'},
        {'term': 'Record Date', 'jp': '基準日', 'desc': '配当や議決権行使等の権利確定の基準となる日。', 'desc_en': 'The date on which shareholders must be on the register to exercise rights.'},
        {'term': 'Cumulative Voting', 'jp': '累積投票', 'desc': '取締役選任で一人に票を集中して投票できる制度。', 'desc_en': 'A voting system allowing concentration of votes for director elections.'},
        {'term': 'Proxy Solicitation', 'jp': '委任状勧誘', 'desc': '株主の議決権行使を委任状で集める手続。', 'desc_en': 'Soliciting proxies for shareholder voting.'},
        {'term': 'Shareholder Proposal Right', 'jp': '株主提案権', 'desc': '一定要件を満たす株主が議案を提出できる権利。', 'desc_en': 'Right of eligible shareholders to submit proposals to the meeting.'},
        {'term': 'Three-Committee Company', 'jp': '指名委員会等設置会社', 'desc': '指名・報酬・監査の3委員会を置く会社形態。', 'desc_en': 'A company with nomination, compensation and audit committees.'},
        {'term': 'Company with Audit Committee', 'jp': '監査等委員会設置会社', 'desc': '取締役会内に監査等委員会を置く会社形態。', 'desc_en': 'A company that has an audit committee within the board.'},
        {'term': 'Small Company Exemptions', 'jp': '小会社の特例', 'desc': '一定の小規模会社に認められる機関設計等の特例。', 'desc_en': 'Special rules for small companies under the Companies Act.'},
        {'term': 'Appraisal Rights', 'jp': '株式買取請求権', 'desc': '合併等に反対した株主が公正価格で買取を請求できる権利。', 'desc_en': 'Right of dissenting shareholders to demand share purchase at a fair price.'},
        {'term': 'Squeeze-out', 'jp': 'スクイーズアウト', 'desc': '少数株主を現金等で排除する手続。', 'desc_en': 'Forcing out minority shareholders for cash consideration.'},
        {'term': 'Share Buyback', 'jp': '自己株式取得', 'desc': '会社が市場買付や公開買付で自社株を取得する行為。', 'desc_en': 'Repurchasing a company’s own shares via market or tender offer.'},
        {'term': 'Dividend in Kind', 'jp': '現物配当', 'desc': '金銭ではなく資産で行う配当。', 'desc_en': 'Distributing dividends in assets rather than cash.'},
        {'term': 'Interim Dividend', 'jp': '中間配当', 'desc': '期中に行う配当。定款の定め等が必要。', 'desc_en': 'A dividend paid before the end of a fiscal year.'},
        {'term': 'Capital Reduction', 'jp': '減資', 'desc': '資本金を減少させる手続。債権者保護手続が必要な場合がある。', 'desc_en': 'Reducing stated capital subject to creditor protections.'},
        {'term': 'Legal Capital Surplus', 'jp': '資本準備金', 'desc': '払込資本のうち資本金に組み入れなかった部分。', 'desc_en': 'Capital reserve from paid-in capital not designated as capital stock.'},
        {'term': 'Reserve Reversal', 'jp': '準備金の取り崩し', 'desc': '準備金を配当原資等に振り替える手続。', 'desc_en': 'Reversing reserves for distribution or other purposes.'},
        {'term': 'Business Report', 'jp': '事業報告', 'desc': '取締役会設置会社が作成する経営状況の報告書。', 'desc_en': 'A report on business operations prepared by certain companies.'},
        {'term': 'Accounting Documents', 'jp': '計算書類', 'desc': '貸借対照表、損益計算書、附属明細書等。', 'desc_en': 'Financial statements and accompanying schedules under Companies Act.'},
        {'term': 'Consolidated Statements', 'jp': '連結計算書類', 'desc': '親会社が作成する連結ベースの計算書類。', 'desc_en': 'Consolidated financial statements prepared by the parent company.'},
        {'term': 'Remuneration Policy', 'jp': '役員報酬方針', 'desc': '取締役等の報酬決定方針と開示。', 'desc_en': 'Policy and disclosure regarding director and officer compensation.'},
        {'term': 'Internal Control System Resolution', 'jp': '内部統制システム整備の決議', 'desc': '取締役会が内部統制基本方針を決議する。', 'desc_en': 'Board resolution on basic policy for internal control systems.'},
        {'term': 'Electronic Public Notice', 'jp': '電子公告', 'desc': 'インターネット上で行う公告方法。', 'desc_en': 'Making statutory public notices via the internet.'},
        {'term': 'Special Controlling Shareholder', 'jp': '特別支配株主', 'desc': '株式等の90%以上を保有し簡易な株式等売渡請求が可能。', 'desc_en': 'A shareholder holding at least 90% enabling squeeze-out procedures.'},
        {'term': 'Share Unit Number', 'jp': '単元株数', 'desc': '議決権の単位となる株式数。', 'desc_en': 'Number of shares that constitute one voting unit.'},
        {'term': 'Share Certificate', 'jp': '株券', 'desc': '発行会社に限り交付される有価証券（原則廃止だが選択可能）。', 'desc_en': 'A physical certificate representing shares if issued.'},
        {'term': 'Director Removal', 'jp': '取締役の解任', 'desc': '株主総会の普通決議でいつでも解任可能（損害賠償請求の可能性あり）。', 'desc_en': 'Directors may be removed by ordinary resolution; damages may be sought.'},
        {'term': 'Director Remuneration Approval', 'jp': '取締役報酬の決議', 'desc': '総額等は株主総会の決議事項。', 'desc_en': 'Shareholders approve the amount/limit of directors’ remuneration.'},
        {'term': 'Business Combination', 'jp': '組織再編', 'desc': '合併、会社分割、株式交換・移転、事業譲渡などの総称。', 'desc_en': 'Mergers, splits, share exchanges/transfers, and business transfers.'},
        {'term': 'Derivative Action Prerequisites', 'jp': '株主代表訴訟の要件', 'desc': '請求手続や保有要件等の規定。', 'desc_en': 'Requirements such as prior demand and shareholding for derivative suits.'},
        {'term': 'Meeting Minutes', 'jp': '議事録の作成・備置', 'desc': '株主総会・取締役会の議事録作成と保管義務。', 'desc_en': 'Preparation and retention of minutes for shareholders and board meetings.'},
        {'term': 'Convocation Notice', 'jp': '招集通知', 'desc': '株主総会開催の通知要件と期間。', 'desc_en': 'Notice requirements and timing for convening shareholders’ meetings.'},
        {'term': 'Place of Head Office', 'jp': '本店所在地', 'desc': '定款記載事項で登記の対象。', 'desc_en': 'Registered head office location stated in articles.'}
    ]
}

# Ensure directory exists
os.makedirs('assets', exist_ok=True)

# Write to file
with open('assets/vocab.json', 'w', encoding='utf-8') as f:
    json.dump(vocab_data, f, indent=4, ensure_ascii=False)

print("assets/vocab.json created successfully.")
